### ISSUE TITLE
RuntimeError: Unable to load caffe network Prototxt file: mobilenet_yolov3_lite_deploy.prototxt

### ISSUE THREAD

**Issue by yizhaoyanbo** [eric612/MobileNet-YOLO#78]
********
[libprotobuf ERROR /Users/zach/builds/4f04be8b/0/turi/coremltools-build/deps/protobuf/src/google/protobuf/text_format.cc:287] Error parsing text-format caffe.NetParameter: 966:33: Message type "caffe.LayerParameter" has no field named "yolov3_detection_output_param".
Traceback (most recent call last):
  File "caffe2coreML.py", line 3, in <module>
    coreml_model = coremltools.converters.caffe.convert(('mobilenet_yolov3_lite_deploy.caffemodel','mobilenet_yolov3_lite_deploy.prototxt'), image_input_names='data')
  File "/Users/riddick/Library/Python/2.7/lib/python/site-packages/coremltools/converters/caffe/_caffe_converter.py", line 191, in convert
    predicted_feature_name)
  File "/Users/riddick/Library/Python/2.7/lib/python/site-packages/coremltools/converters/caffe/_caffe_converter.py", line 255, in _export
    predicted_feature_name)
RuntimeError: Unable to load caffe network Prototxt file: mobilenet_yolov3_lite_deploy.prototxt

***********

I wanna to convert  " mobilenet_yolov3_lite_deploy.caffemodel " to  mlModel.  But this error occurs.
 the convert code is following:

************

import coremltools

coreml_model = coremltools.converters.caffe.convert(('mobilenet_yolov3_lite_deploy.caffemodel','mobilenet_yolov3_lite_deploy.prototxt'), image_input_names='data')

coreml_model.save('cmlModel.mlmodel')

*************

Anyone has the same problem?

**Comment by eric612** [comment]
Remove yolov3 detection output layer and try it again

yizhaoyanbo <notifications@github.com> 於 2019年3月7日 週四 下午6:48 寫道：
